longhorn/infra

- jenkins-jobs/longhorn-tests.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
> add longhorn jenkins jobs

- overrides/jenkins-values.yaml
> add slack notification plugin to jenkins overrides

- overrides/jenkins-values.yaml
- update pipeline-stage-step to v2.5
- update jackson2-api to v2.11.1
- update credentials to v2.3.11
> Update Jenkins plugins

- overrides/grafana-values.yaml
> Add grafana chart override values

- overrides/drone-pr-values.yaml
> Add drone-pr chart override values

- overrides/drone-pr-values.yaml
> Fix typos in drone-pr chart override values

- overrides/drone-publish-values.yaml
> Add drone-publish chart override values

- jenkins-jobs/folders.yml
> add folders for public and private jobs

- jenkins-jobs/longhorn-tests.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
> move nightly test jobs to public folder

- overrides/jenkins-values.yaml
> add project level authentication for private jobs

- jenkins-jobs/secscan.yml
> add image security scanning job

- overrides/jenkins-values.yaml
- Added plugin:
- Extended Choice Parameter plugin
- Upgraded plugins:
- Matrix Project 
- Matrix Authorization Strategy
> Add and upgrade Jenkins plugins

- jenkins-jobs/secscan.yml
> add severity options and trigger time to image security scan job

- overrides/drone-publish-values.yaml
> increase nginx max client body size for drone publish

- jenkins-jobs/longhorn-v1.0.x-tests.yml
> add longhorn nightly tests job for v1.0.x

- jenkins-jobs/longhorn-v1.0.x-tests.yml
LONGHORN_UPGRADE_TEST
LONGHORN_TEST_CLOUDPROVIDER
> add missing env variables to longhorn v1.0.x job

- overrides/jenkins-values.yaml
> add test result analyzer plugin to jenkins overrides

- jenkins-jobs/longhorn-tests-regression.yml
https://github.com/longhorn/longhorn-tests/pull/408
> add longhorn-tests-regression jobs

- jenkins-jobs/longhorn-tests.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
> add missing parameters for integration tests jobs

- jenkins-jobs/longhorn-tests.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
> add custom images parameters to jenkins jobs

- jenkins-jobs/longhorn-tests-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
> add arm64 support to longhorn nightly tests

- jenkins-jobs/longhorn-tests-arm64.yml
> fix job name typo

- jenkins-jobs/longhorn-tests-arm64.yml
- jenkins-jobs/longhorn-tests.yml
- jenkins-jobs/longhorn-upgrade-tests-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
- jenkins-jobs/longhorn-v1.0.x-tests.yml
- jenkins-jobs/secscan.yml
> start nightly tests one hour earlier

- jenkins-jobs/longhorn-tests-arm64.yml
- jenkins-jobs/longhorn-tests.yml
- jenkins-jobs/longhorn-upgrade-tests-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests.yml
- jenkins-jobs/longhorn-v1.0.x-tests.yml
- jenkins-jobs/secscan.yml
> change nightly tests trigger time to be 9:00 PM

- jenkins-jobs/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-arm64.yml
> add RHEL jenkins jobs

- jenkins-jobs/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-arm64.yml
REF: https://github.com/longhorn/longhorn-tests/pull/533
> update longhorn nightly tests jobs

- jenkins-jobs/longhorn-tests-sles-amd64.yml
- jenkins-jobs/longhorn-tests-sles-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-arm64.yml
> add SUSE SLES jenkins jobs

- jenkins-jobs/folders.yml
> add distro folders

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-tests-sles-amd64.yml
- jenkins-jobs/longhorn-tests-sles-arm64.yml
- jenkins-jobs/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-arm64.yml
REF: https://github.com/longhorn/longhorn-tests/pull/538
> modify jenkins jobs to support run tests using custom images

- jenkins-jobs/longhorn-upgrade-tests-ubuntu-arm64.yml
> fix jenkins jobs duplicate name

- jenkins-jobs/longhorn-v1.0.x-tests.yml
> disabled longhorn v1.0.x nightly tests

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-tests-sles-amd64.yml
- jenkins-jobs/longhorn-tests-sles-arm64.yml
- jenkins-jobs/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-arm64.yml
> update jenkins jobs to support slack channel change

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-tests-sles-amd64.yml
- jenkins-jobs/longhorn-tests-sles-arm64.yml
- jenkins-jobs/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/longhorn-upgrade-tests-ubuntu-arm64.yml
> change aws region & availability zone for nightly tests

- jenkins-jobs/folders.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-arm64.yml
> move jobs to master folder, and create v1.1.2 jobs

- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-arm64.yml
> fix v1.1.2 job folders

- jenkins-jobs/jenkins-job-builder.yml
> add yaml files recursively

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-arm64.yml
https://github.com/longhorn/longhorn/issues/2628
> Add ability to run nightly regression nightly tests using customize baking image manager image

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-arm64.yml
https://github.com/longhorn/longhorn/issues/2713
> use v1.1.1 as stable version in nighly upgrade test

- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.2/longhorn-upgrade-tests-ubuntu-arm64.yml
https://github.com/longhorn/longhorn/issues/2784
> temporarily disable v1.1.2 nightly tests.

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
> enable v1.1.3 nightly tests

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
Ref: https://github.com/longhorn/longhorn-tests/pull/694
> Modify default slack notification channel

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
> Revert "Modify default slack notification channel"

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
> add nightly tests for v1.2.x

- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
https://github.com/longhorn/longhorn/issues/3045
> jenkins: upgrade nightly tests OS disto versions

- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
v1.1.3: upgrade from v1.1.2
v1.2.1: upgrade from v1.2.0
master: upgrade from v1.2.0
> update longhorn stable version for upgrade test

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
https://github.com/longhorn/longhorn/issues/3045
> Fix wrong RHEL distro version and edit distro descriptions across all jobs

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
> set RHEL default OS version to 8.3

- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-nfs-only.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-s3-only.yml
https://github.com/longhorn/longhorn/issues/2999
> Separate s3 and nfs tests

- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-nfs-only.yml
> Fix format

- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-nfs-only.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-s3-only.yml
> fix duplicate nfs and s3 job names

- jenkins-jobs/master/longhorn-tests-ubuntu-amd64.yml
Fix the auto trigger with parameterized cron.
> Fix auto trigger for ubuntu amd Job

- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
> Add parameterized trigger to upgrade

- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
> Add parameterized trigger

- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
> Add parameterized trigger for master-arm job

- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-amd64.yml
> fix ubuntu job triggers

- jenkins-jobs/master/centos/longhorn-tests-centos-amd64.yml
- jenkins-jobs/master/centos/longhorn-tests-centos-arm64.yml
- jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-amd64.yml
- jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-arm64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
Ref: https://github.com/longhorn/longhorn/issues/3310
> add arm64 and selinux support

- jenkins-jobs/master/centos/longhorn-tests-centos-arm64.yml
- jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
> add arm64 folders for centos and rockylinux

- jenkins-jobs/master/centos/longhorn-tests-centos-arm64.yml
- jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
> Revert "add arm64 folders for centos and rockylinux"

- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.3/longhorn-upgrade-tests-ubuntu-arm64.yml
> disable daily run for v1.1.3 & v1.2.3

- jenkins-jobs/master/centos/longhorn-tests-centos-amd64.yml
- jenkins-jobs/master/centos/longhorn-tests-centos-arm64.yml
- jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-amd64.yml
- jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-arm64.yml
- jenkins-jobs/master/oracle/longhorn-tests-oracle-amd64.yml
- jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-arm64.yml
Ref: https://github.com/longhorn/longhorn/issues/3243
> add k8s_distro_name and k8s_distro_version parameters & run SLES nightly by default 

- jenkins-jobs/longhorn-tests-regression.yml
> update longhorn regreesion job

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.1.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.1.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.1.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.1.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-arm64.yml
Ref: https://github.com/longhorn/longhorn/issues/3559
> enable nightly integration for v1.2.x and 1.1.x

- jenkins-jobs/v1.1.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.1.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.1.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.1.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-arm64.yml
> fix v1.1.x and v1.2.x job names

- jenkins-jobs/jenkins-job-builder.yml
> add flush cache to jenkins job builder command

- overrides/drone-pr-values.yaml
- overrides/drone-publish-values.yaml
- overrides/grafana-values.yaml
- overrides/jenkins-values.yaml
> update infra overrides

- jenkins-jobs/longhorn-benchmark-test.yml
to run kbench and record results periodically
for issue [#3540](https://github.com/longhorn/longhorn/issues/3540)
> Add jenkins job yaml for performance test

- jenkins-jobs/mirror-csi-images.yml
Add job for mirror csi images
For [#3056](https://github.com/longhorn/longhorn/issues/3056)
> Add job for mirror csi images

- overrides/jenkins-values.yaml
Sync matrix plugins versions in jenkins-values.yaml and remove duplicated one
> Sync matrix plugins versions in jenkins-values.yaml 

- jenkins-jobs/longhorn-benchmark-test.yml
Run benchmark test for customized longhorn
For [#3919](https://github.com/longhorn/longhorn/issues/3919)
> Run benchmark test for customized longhorn

- jenkins-jobs/folders.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/secscan.yml
- jenkins-jobs/v1.1.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.1.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.1.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.1.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
(1) Add v1.3.x pipeline
(2) Disable v1.1.x pipeline
(3) Adjust cron jobs timezone to Asia/Taipei
for https://github.com/longhorn/longhorn/issues/4123
> Add v1.3.x pipeline and Disable v1.1.x pipeline

- overrides/jenkins-values.yaml
Update jenkins plugins to add Longhorn version information on the build summary page
For https://github.com/longhorn/longhorn/issues/4204
> Update jenkins plugins to add Longhorn version information on the build summary page

- jenkins-jobs/longhorn-tests-regression.yml
Add option for HDD test
For https://github.com/longhorn/longhorn/issues/4182
> Add option for HDD test

- jenkins-jobs/longhorn-tests-regression.yml
- overrides/jenkins-values.yaml
Setup pipeline for testing longhorn air gap installation.
for https://github.com/longhorn/longhorn/issues/3926
> Setup pipeline for testing longhorn air gap installation.

- jenkins-jobs/longhorn-tests-regression.yml
Add option for rancher air gap installation
for https://github.com/longhorn/longhorn/issues/3926
> Add option for rancher air gap installation

- jenkins-jobs/longhorn-tests-regression.yml
ci: add code flow to create new secret in air gap installation
For https://github.com/longhorn/longhorn/issues/4480
> ci: add code flow to create new secret in air gap installation

- jenkins-jobs/longhorn-tests-regression.yml
This reverts commit a9e9eece351529eacb2c6c4e606311065c2196a8.
> Revert "ci: add code flow to create new secret in air gap installation"

- jenkins-jobs/longhorn-tests-regression.yml
ci: update supported distro version info
> ci: update supported distro version info

- jenkins-jobs/cleanup-resources.yml
ci: pipeline for deleting unexpected long-running testing resources
For https://github.com/longhorn/longhorn/issues/3913
> ci: pipeline for deleting unexpected long-running testing resources

- jenkins-jobs/longhorn-benchmark-test.yml
test: running different versions of longhorn in the same benchmark test build for comparison
For https://github.com/longhorn/longhorn/issues/4259
> test: running different versions of longhorn in the same benchmark test build for comparison

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
test: implement 2 stage upgrade
For https://github.com/longhorn/longhorn/issues/4817
> test: implement 2 stage upgrade

- jenkins-jobs/longhorn-benchmark-test.yml
ci: setup benchmark test environment on equinix metal
https://github.com/longhorn/longhorn/issues/3885
> ci: setup benchmark test environment on equinix metal

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
ci: add v1.4.x pipeline
For https://github.com/longhorn/longhorn/issues/5052
> ci: add v1.4.x pipeline

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
ci: update k8s and os version info
For https://github.com/longhorn/infra/pull/111#discussion_r1048200657
> ci: update k8s and os version info

- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-arm64.yml
ci: disable v1.2.x daily run because of EOL
> ci: disable v1.2.x daily run because of EOL

- jenkins-jobs/longhorn-benchmark-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
ci: update aws availability zone to avoid insufficient capacity issue
For https://github.com/longhorn/longhorn/issues/5389
> ci: update aws availability zone to avoid insufficient capacity issue

- jenkins-jobs/folders.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
ci: add sle-micro provisioning
For https://github.com/longhorn/longhorn/issues/5675
> ci: add sle-micro provisioning

- jenkins-jobs/folders.yml
- jenkins-jobs/managed-k8s/longhorn-tests-aks.yml
- jenkins-jobs/managed-k8s/longhorn-tests-eks.yml
- jenkins-jobs/managed-k8s/longhorn-tests-gke.yml
ci: add managed k8s provisioning
For https://github.com/longhorn/longhorn/issues/4621
> ci: add managed k8s provisioning

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
ci: update upgrade path in master pipeline
> ci: update upgrade path in master pipeline

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
ci: add v1.5.x pipelines
Signed-off-by: Chris <chris.chien@suse.com>
> ci: add v1.5.x pipelines

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/oracle/longhorn-tests-oracle-amd64.yml
- jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
ci: update os and k8s distro info
> ci: update os and k8s distro info

- jenkins-jobs/longhorn-helm-chart-test.yml
ci: add helm install/upgrade regression test pipeline
For https://github.com/longhorn/longhorn/issues/3987
> ci: add helm install/upgrade regression test pipeline

- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
change upgrade test versions to v1.4.3 in v1.5.x pipeline
> change upgrade test versions to v1.4.3 in v1.5.x pipeline

- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
Follow code pattern, change upgrade test versions from v1.4.2 to v1.4.3 in v1.4.x pipeline
> change upgrade test versions to v1.4.3 in v1.4.x pipeline

- jenkins-jobs/longhorn-helm-chart-test.yml
- jenkins-jobs/longhorn-rancher-chart-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
ci: update sles version to 15-sp5
For https://github.com/longhorn/longhorn/issues/6462
> ci: update sles version to 15-sp5

- jenkins-jobs/longhorn-argocd-test.yml
ci: add argocd install/upgrade regression test pipeline
For https://github.com/longhorn/longhorn/issues/3987 https://github.com/longhorn/longhorn/issues/6434
> ci: add argocd install/upgrade regression test pipeline

- jenkins-jobs/longhorn-flux-test.yml
ci: add flux install/upgrade regression test pipeline
For https://github.com/longhorn/longhorn/issues/3987 https://github.com/longhorn/longhorn/issues/6343
> ci: add flux install/upgrade regression test pipeline

- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
ci: disable eol v1.3.x daily regression
> ci: disable eol v1.3.x daily regression

- jenkins-jobs/longhorn-e2e-test.yml
test: add negative testing pipeline
For https://github.com/longhorn/longhorn/issues/6499
> test: add negative testing pipeline

- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
infra: update v1.4.x k8s version to v1.27
> infra: update v1.4.x k8s version to v1.27

- overrides/grafana-values.yaml
> Update grafana chart for metric dashboard

- jenkins-jobs/longhorn-storage-network-test.yml
ci: add pipeline for storage network
For https://github.com/longhorn/longhorn/issues/4218
> ci: add pipeline for storage network

- jenkins-jobs/longhorn-tests-regression.yml
infra: add custom ssh public key for debugging
For https://github.com/longhorn/longhorn/issues/7307
> infra: add custom ssh public key for debugging

- jenkins-jobs/longhorn-fleet-test.yml
ci: add pipeline for fleet
For https://github.com/longhorn/longhorn/issues/6935
> ci: add pipeline for fleet

- overrides/jenkins-values.yaml
infra: sync jenkins-values.yaml for new plugins installed
For https://github.com/longhorn/longhorn/issues/7166 which requires HTML Publisher
And https://github.com/longhorn/longhorn/issues/5240 which requires robot
And increase memory for OOM
> infra: sync jenkins-values.yaml for new plugins installed

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
ci: add v1.6.x pipelines
For https://github.com/longhorn/longhorn/issues/7665
> ci: add v1.6.x pipelines

- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
ci: update v1.6.x upgrade test stable version
For https://github.com/longhorn/longhorn/issues/7665
> ci: update v1.6.x upgrade test stable version

- jenkins-jobs/longhorn-argocd-test.yml
- jenkins-jobs/longhorn-e2e-test.yml
- jenkins-jobs/longhorn-fleet-test.yml
- jenkins-jobs/longhorn-flux-test.yml
- jenkins-jobs/longhorn-helm-chart-test.yml
- jenkins-jobs/longhorn-rancher-chart-test.yml
- jenkins-jobs/longhorn-storage-network-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/oracle/longhorn-tests-oracle-amd64.yml
- jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
ci: update oracle/rhel distro version
For https://github.com/longhorn/longhorn/issues/7653
> ci: update oracle/rhel distro version

- jenkins-jobs/longhorn-tests-regression.yml
ref: [3978](https://github.com/longhorn/longhorn/issues/3978)
Have a setting on pipline to enalbe mtls
https://longhorn.io/docs/1.6.0/advanced-resources/security/mtls-support/
together with https://github.com/longhorn/longhorn-tests/pull/1791
> ci: add mtls test

- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
ci: disable v1.4.x daily regression
> ci: disable v1.4.x daily regression

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
> Update v1.5.x LONGHORN_STABLE_VERSION to v1.5.4

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
ci: reduce aws cost by triggering less daily regressions
For https://github.com/longhorn/longhorn/issues/8414
> ci: reduce aws cost by triggering less daily regressions

- jenkins-jobs/longhorn-e2e-test.yml
ci: add option of v2 test for robot test
For https://github.com/longhorn/longhorn/issues/7202
> ci: add option of v2 test for robot test

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
> Update v1.5.x `LONGHORN_STABLE_VERSION` to `v1.5.5`

- jenkins-jobs/longhorn-rancher-chart-test.yml
ci: support rancher prime
For https://github.com/longhorn/longhorn/issues/8499
> ci: support rancher prime

- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-arm64.yml
> Update ubuntu job distro version to 24.04

- jenkins-jobs/longhorn-e2e-test.yml
ci: update robot test default parameters
> ci: update robot test default parameters

- jenkins-jobs/longhorn-argocd-test.yml
- jenkins-jobs/longhorn-e2e-test.yml
- jenkins-jobs/longhorn-fleet-test.yml
- jenkins-jobs/longhorn-flux-test.yml
- jenkins-jobs/longhorn-helm-chart-test.yml
- jenkins-jobs/longhorn-rancher-chart-test.yml
- jenkins-jobs/longhorn-storage-network-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
ref. longhorn/longhorn#8958
1. amd64: https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/185/
- amd64 Rerun Failed Cases: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7176/
2. arm64: https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-arm64/180/
> Update SLES version to 15-sp6

- jenkins-jobs/folders.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.7.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.7.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.7.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.7.x/longhorn-upgrade-tests-sles-arm64.yml
> ci: add v1.7.x jenkins jobs

- overrides/jenkins-values.yaml
infra: update jenkins permission matrix format
> infra: update jenkins permission matrix format

- jenkins-jobs/longhorn-argocd-test.yml
- jenkins-jobs/longhorn-e2e-test.yml
- jenkins-jobs/longhorn-fleet-test.yml
- jenkins-jobs/longhorn-flux-test.yml
- jenkins-jobs/longhorn-helm-chart-test.yml
- jenkins-jobs/longhorn-rancher-chart-test.yml
- jenkins-jobs/longhorn-storage-network-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-arm64.yml
ci: update sle-micro version to 6.0
For https://github.com/longhorn/longhorn/issues/9001
> ci: update sle-micro version to 6.0

- jenkins-jobs/managed-k8s/longhorn-tests-aks.yml
- jenkins-jobs/managed-k8s/longhorn-tests-gke.yml
test: ignore test_offline_node in gke and aks
For https://github.com/longhorn/longhorn/issues/7720
> test: ignore test_offline_node in gke and aks

- jenkins-jobs/folders.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/talos/longhorn-tests-talos-amd64.yml
- jenkins-jobs/master/talos/longhorn-upgrade-tests-talos-amd64.yml
ci: add talos pipeline
For https://github.com/longhorn/longhorn/issues/6596
> ci: add talos pipeline

- jenkins-jobs/longhorn-tests-regression.yml
Set default values for `CUSTOM_LONGHORN_INSTANCE_MANAGER_IMAGE`, `CUSTOM_LONGHORN_SHARE_MANAGER_IMAGE`, and `CUSTOM_LONGHORN_BACKING_IMAGE_MANAGER_IMAGE` in  longhorn-regression-test job input fields.
> Update longhorn-regression-test job parameter

- jenkins-jobs/longhorn-tests-regression.yml
revert commit  https://github.com/longhorn/infra/commit/51f5dcc8322816e926b455d9b148c0cf661bc555 because it causes the longhorn-regression-test to display incorrectly.
> Revert Update longhorn-regression-test job parameter

- jenkins-jobs/longhorn-tests-regression.yml
ci: remove unused dynamic options
> ci: remove unused dynamic options

- jenkins-jobs/build-engine-test-images.yml
ci: fix syntax error in block formatting
> ci: fix syntax error in block formatting

- jenkins-jobs/build-engine-test-images.yml
ci: avoid string substitution issue
> ci: avoid string substitution issue

- jenkins-jobs/folders.yml
- jenkins-jobs/master/talos/longhorn-tests-talos-arm64.yml
- jenkins-jobs/master/talos/longhorn-upgrade-tests-talos-amd64.yml
- jenkins-jobs/master/talos/longhorn-upgrade-tests-talos-arm64.yml
ci: add talos arm64 pipeline
For https://github.com/longhorn/longhorn/issues/6596
> ci: add talos arm64 pipeline

- jenkins-jobs/secscan.yml
ci: run security scanning for actively supported branches
For https://github.com/longhorn/longhorn/issues/9869
> ci: run security scanning for actively supported branches

- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-arm64.yml
> ci: fix duplicate job

- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-arm64.yml
> ci: fix folder not exist

- jenkins-jobs/master/sles/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-arm64.yml
ci: refine default robot custom options
> ci: refine default robot custom options

- jenkins-jobs/master/sles/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-arm64.yml
ci: include backslash in robot custom options default value
> ci: include backslash in robot custom options default value

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
ci: support v2 volume on daily regression
For https://github.com/longhorn/longhorn/issues/9760
> ci: support v2 volume on daily regression

- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.8.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.8.x/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.8.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.8.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.8.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.8.x/longhorn-upgrade-tests-sles-arm64.yml
> ci: add v1.8.x pipelines

- jenkins-jobs/folders.yml
> ci: add v1.8.x folder
