longhorn/infra

- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
use default instance-manager, share-manager and backing-image-manager images in v1.1.3
> use default instance-manager, share-manager and backing-image-manager images in v1.1.3

- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
job name is used as prefix to instances names, and names needs to be less than 64 characters to be valid.
> change test jobs names to descrease it's length

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-nfs-only.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-amd64-s3-only.yml
- jenkins-jobs/master/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.1.3/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/v1.2.1/longhorn-upgrade-tests-ubuntu-arm64.yml
Fix for auto trigger of the jobs nfs and s3 only and addition of variable in all the config files so that they don't fail.
> fix the auto trigger and add the variable at config file

- jenkins-jobs/jenkins-job-builder.yml
- overrides/jenkins-values.yaml
Cache jenkins job builder to prevent private folder setting from overwritten.
For https://github.com/longhorn/longhorn/issues/3960
> Cache jenkins job builder

- jenkins-jobs/secscan.yml
ci: support running secscan test on specified longhorn branch/version
For https://github.com/longhorn/longhorn/issues/4357
> ci: support running secscan test on specified longhorn branch/version

- jenkins-jobs/build-engine-test-images.yml
Signed-off-by: Chris Chien <chris.chien@suse.com>
https://github.com/longhorn/longhorn/issues/4615
Add param `COMMIT_ID` in build-engine-test-images pipeline
In case we need to build old API version engine upgrade test images
Longhorn v1.2.x engine upgrade test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2067/) with [upgrade-test.5-3.3-3.1-1](https://hub.docker.com/layers/chanow/longhorn-manager-test/upgrade-test.5-3.3-3.1-1/images/sha256-14237c8bac6c32fc44552e37b76199b1e7b6683052e42c4f879e8b6ac5f1bf84?context=repo) 
Longhorn master-head engine upgrade test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2068/) with [upgrade-test.6-3.3-3.1-1](https://hub.docker.com/layers/chanow/longhorn-test/upgrade-test.6-3.3-3.1-1/images/sha256-1d1 …
> Add param COMMIT_ID in build-engine-test-images pipeline

- jenkins-jobs/longhorn-benchmark-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
ci: set sles default version to 15-sp4 and update rocky/rhel/oracle version info
For https://github.com/longhorn/longhorn/issues/4620, https://github.com/longhorn/longhorn/issues/4618
> ci: set sles default version to 15-sp4 and update rocky/rhel/oracle version info

- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
ci: update default k8s version to v1.25 on master branch
for k3s, update to v1.25.3+k3s1
for rke2, update to v1.25.3+rke2r1
for rke, it doesn't support k8s v1.25 yet
For https://github.com/longhorn/longhorn/issues/4239
> ci: update default k8s version to v1.25 on master branch

- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
ci: revert master pipeline upgrade test k8s version to < v1.25 to prevent upgrade test failed
because in upgrade test a previous version of longhorn which doesn't support k8s v1.25 will be installed first 
For https://github.com/longhorn/longhorn/issues/4239
> ci: revert master pipeline upgrade test k8s version to < v1.25 to prevent upgrade test failed

- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
test: add different upgrade paths to cover upgrading from the previous branch release
for upgrade to master, 2 upgrade paths are:
(1) v1.2.6 -> master
(2) v1.3.2 -> master
for upgrade to v1.3.x, 2 upgrade paths are:
(1) v1.2.6 -> v1.3.x
(2) v1.3.2 -> v1.3.x
For https://github.com/longhorn/longhorn/issues/4706
> test: add different upgrade paths to cover upgrading from the previous branch release

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
ci: fix duplicated job name causes build jenkins jobs failed
> ci: fix duplicated job name causes build jenkins jobs failed

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.2.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
update sles 15 sp4 image version from 15-sp4-v20220621 to 15-sp4-v20220722, since 15-sp4-v20220621 has been removed.
> ci: update sles 15 sp4 image version

- jenkins-jobs/build-engine-test-images.yml
ci: run build-engine-test-images automatically
For https://github.com/longhorn/longhorn/issues/5400
> ci: run build-engine-test-images automatically

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.3.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
ci: shift daily regression cron jobs 2 hours earlier
For https://github.com/longhorn/longhorn/issues/5661
> ci: shift daily regression cron jobs 2 hours earlier

- jenkins-jobs/managed-k8s/longhorn-tests-gke.yml
ci: refactor to have separate gke pipeline
Refine gke pipeline parameters to match with the changes in longhorn-tests
For https://github.com/longhorn/longhorn/issues/6031
> ci: refactor to have separate gke pipeline

- jenkins-jobs/longhorn-tests-regression.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
#longhorn/longhorn#5595
The RKE2 install scripts we use can no longer locate v1.27.1+rke2r1. Use v1.27.2+rke2r1 instead.
> Use obtainable RKE2 version for tests

- jenkins-jobs/master/rhel/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-tests-ubuntu-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-tests-sles-arm64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
ci: use a1.2xlarge machine for arm64
(1) use a1.2xlarge machine for arm64 test to fix test_support_bundle_should_not_timeout failure
(2) add 2 stage upgrade test parameter for v1.5.x and v1.4.x
For https://github.com/longhorn/longhorn-tests/pull/1456
> ci: use a1.2xlarge machine for arm64

- jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-amd64.yml
- jenkins-jobs/master/ubuntu/longhorn-upgrade-tests-ubuntu-arm64.yml
Update upgrade test version in master pipeline for v1.5.0 released
(1) upgrade test: LONGHORN_STABLE_VERSION=v1.5.0
(2) 2 stage upgrade test: LONGHORN_STABLE_VERSION=v1.4.3, LONGHORN_TRANSIENT_VERSION=v1.5.0
> update master pipeline upgrade test version

- jenkins-jobs/longhorn-tests-regression.yml
ci: add cis-1.23 hardening in sles rke2 terraform script
For https://github.com/longhorn/longhorn/issues/6092
> ci: add cis-1.23 hardening in sles rke2 terraform script

- jenkins-jobs/longhorn-rancher-chart-test.yml
ci: add rancher chart install/upgrade regression test pipeline
For https://github.com/longhorn/longhorn/issues/3987
> ci: add rancher chart install/upgrade regression test pipeline

- jenkins-jobs/longhorn-rancher-chart-test.yml
ci: add rancher version and longhorn repo name as options in rancher pipeline
For https://github.com/longhorn/longhorn/issues/3987
> ci: add rancher version and longhorn repo name as options in rancher pipeline

- jenkins-jobs/longhorn-tests-regression.yml
ci: add option to assign public ip to worker nodes
For https://github.com/longhorn/longhorn/issues/6601
> ci: add option to assign public ip to worker nodes

- jenkins-jobs/managed-k8s/longhorn-tests-aks.yml
test: skip zone related test cases by default when running on aks
For https://github.com/longhorn/longhorn/issues/7709
> test: skip zone related test cases by default when running on aks

- jenkins-jobs/longhorn-rancher-chart-test.yml
1. Update the `longhorn-rancher-chart-test` pipeline job parameters for Rancher `v2.8.x`
2. Add some comments and examples to the Jenkins job to make it easier for users to understand and use.
ref. longhorn/longhorn#8704
> Update `longhorn-rancher-chart-test` job parameter for Rancher v2.8.x

- jenkins-jobs/longhorn-e2e-test.yml
ci: make robot test be able to run out of cluster
> ci: make robot test be able to run out of cluster

- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/32/console
```
Error: Error launching source instance: Unsupported: Your requested instance type (a1.2xlarge) is not supported in your requested Availability Zone (us-east-1c). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1d.
status code: 400, request id: cc24bd28-1885-4151-a532-c764f06e8bcb
```
> Update rockylinux arm64 `AWS_AVAILABILITY_ZONE`

- jenkins-jobs/managed-k8s/longhorn-tests-eks.yml
ci: skip test_zone in eks because topology.kubernetes.io/zone is set to aws region (like us-east-1a) and cannot be modified even with label --overwrite command
> ci: skip test_zone in eks

- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
ci: update rockylinux aws avaiablility zone to us-east-1a which supports a1.2xlarge instance
> ci: update rockylinux aws avaiablility zone to us-east-1a which supports a1.2xlarge instance

- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-tests-sle-micro-arm64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-amd64.yml
- jenkins-jobs/master/sle-micro/longhorn-upgrade-tests-sle-micro-arm64.yml
Change the default backup store on the `sle-micro` pipeline to avoid using the default setting which causes test pod crash hours later.
test result and ref: https://github.com/longhorn/infra/pull/188#issuecomment-2277209000
> ci: use single backupstore on sle-micro pipeline to avoid test pod crash

- jenkins-jobs/managed-k8s/longhorn-tests-gke.yml
ci: add an option to support gke COS_CONTAINERD
For https://github.com/longhorn/longhorn/issues/8195
> ci: add an option to support gke COS_CONTAINERD

- jenkins-jobs/longhorn-e2e-test.yml
ci: add custom ssh public key option to longhorn-e2e-test to allow team members to access test cluster
For https://github.com/longhorn/longhorn/issues/7307
> ci: add custom ssh public key option to longhorn-e2e-test to allow team members to access test cluster

- jenkins-jobs/longhorn-rancher-chart-test.yml
1. Update the `longhorn-rancher-chart-test` pipeline job parameters for LH `v1.7.1`
2. Update some examples to the Jenkins job to make it easier for users to use.
3. Verify Longhorn  LH v1.7.1 on  Rancher chart Rancher `v2.7.10` : 
- https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/134/
4. Verify Longhorn  LH v1.7.1 on  Rancher chart Rancher `v2.8.5` 
- https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/132/
6.  Verify Longhorn  LH v1.7.1 on  Rancher chart Rancher `v2.9.2` 
- https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/128/
> Update longhorn-rancher-chart-test job parameter for LH v1.7.1

- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-2-stage-upgrade-tests-sles-arm64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-upgrade-tests-sles-arm64.yml
Update SLES pipelines to ensure compatibility with all active Kubernetes versions.
- Enable E2E tests to run on rke2/k3s `v1.31.x`.
- Upgrade test support rke2/k3s `v1.30.x`.
- 2-stage upgrade test support rke2/k3s `v1.29.x`.
**Ref.**
> Enhance SLES Pipelines for k8s Version Compatibility

- jenkins-jobs/master/oracle/longhorn-tests-oracle-amd64.yml
- jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-tests-rhel-arm64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-amd64.yml
- jenkins-jobs/master/rhel/longhorn-upgrade-tests-rhel-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-tests-rockylinux-arm64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-amd64.yml
- jenkins-jobs/master/rockylinux/longhorn-upgrade-tests-rockylinux-arm64.yml
https://github.com/longhorn/longhorn/issues/9879
* Rockylinux, `9.5`
* RHEL `9.5.0`
* Oracle `9.4`
> ci: Bump OS distro version for Longhorn v1.8.0

- jenkins-jobs/longhorn-e2e-test.yml
- jenkins-jobs/longhorn-tests-regression.yml
ci: update `BACKUP_STORE_TYPE` description for `cifs` and `azurite` in longhorn-tests-regression.yml and longhorn-e2e-test.yml
https://github.com/longhorn/longhorn/issues/9699
https://github.com/longhorn/longhorn-tests/pull/2155
> ci: update BACKUP_STORE_TYPE description for cifs and azurite

- jenkins-jobs/master/sles/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/master/sles/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.6.x/longhorn-e2e-tests-sles-arm64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-amd64.yml
- jenkins-jobs/v1.7.x/longhorn-e2e-tests-sles-arm64.yml
ci: automatically run robot regression and negative tests daily and weekly
For https://github.com/longhorn/longhorn/issues/9679
> ci: automatically run robot regression and negative tests daily and weekly

- jenkins-jobs/longhorn-tests-regression.yml
For longhorn/longhorn#[2170](https://github.com/longhorn/longhorn-tests/pull/2170)
Enable `RUN_V2_TEST` on Jenkins and use pytest mark `-m v2_volume_test` for using v2 volume in regression test. Some test case not support v2 volume and logged [here](https://github.com/longhorn/longhorn/issues/9760)
> Support v2 volume on daily regression
